[build]
  command = "npm run build container-app && cp _redirects _headers dist/container-app/"
  publish = "dist/container-app"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- projects/container-app/"