[build]
  command = "npm run build calculator && cp _redirects _headers dist/calculator/"
  publish = "dist/calculator"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- projects/calculator"
